
﻿﻿var remotexml = '\n' +
	'	\n' +
	'	<p>As explained in our privacy policy, this Site collects information through the use of "cookies" or similar technologies. Cookies are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site.</p>\n' +
	'	\n' +
	'	<p>The table below explains the main cookies set by this site and their purpose.</p>\n' +
	'	\n' +
	'	<table class="cookies">\n' +
	'		<thead>\n' +
	'			<tr>\n' +
	'				<th>Service</th>\n' +
	'				<th>Cookie Name</th>\n' +
	'				<th>Purpose</th>\n' +
	'				<th>More Info</th>\n' +
	'			</tr>	\n' +
	'		</thead>\n' +
	'		<tbody>\n' +
	'			<tr><td>PHP</td><td>elsevier</td><td>This session cookie, provided by the The PHP Group, stores and tracks data for a user while travelling through a series of pages on the site.</td><td/></tr>\n' +
	'	<tr><td rowspan="4">Google Analytics</td><td>__utma</td><td rowspan="4">These web analytics cookies, provided by Google Inc., are used to collect information about how visitors use our site. We use the information to compile reports and to help us improve the site. The cookies collect information in an anonymous form, including the number of visitors to the site, where visitors have come to the site from and the pages they visited.</td><td rowspan="4">See <a href="http://www.google.co.uk/intl/en/analytics/privacyoverview.html">Cookies Set by Google Analytics and Google Analytics Privacy Overview</a></td></tr><tr><td>__utmb</td></tr><tr><td>__utmc</td></tr><tr><td>__utmz</td></tr>\n' +
	'	\n' +
	'		</tbody>\n' +
	'	</table>\n' +
	'	\n' +
	'	<h2>Option to decline use of cookies</h2>\n' +
	'	<p>As explained in this Site\'s privacy policy, you can prevent your browser from accepting certain cookies, have the browser require your consent before a new cookie is placed in your browser, or block cookies altogether by selecting the appropriate settings on your browser\'s privacy preferences menu. To avoid receiving cookies on the browser of your mobile device, you will need to refer to its user manual. For information on how to opt-out of cookies set by our suppliers, please visit the applicable links listed in the tables above.</p>\n' +
	'	\n' +
	'	<!-- removed because redundant\n' +
	'	<h2>Google Analytics Service</h2>\n' +
	'	<p>This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies," which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google\'s behalf. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>\n' +
	'	-->\n' +
	'	\n' +
	'	<p class="revision">Last revised: 07 June 2012</p>\n' +
	'	\n' +
	'	';